CREATE TABLE "User" (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Password VARCHAR2(128) NOT NULL,
    Email VARCHAR2(128) NOT NULL,
    Permission NUMBER(1) NOT NULL,
    FirstName VARCHAR2(128) NOT NULL,
    LastName VARCHAR2(128) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (ID),
    CONSTRAINT u_user UNIQUE (Email)
);

CREATE TABLE UserData (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Gender VARCHAR2(6),
    ProfilePicture VARCHAR2(128),
    BirthDate DATE,
    PhoneNumber NUMBER,
    Profession VARCHAR2(128),
    UserID NUMBER,
    CONSTRAINT pk_userData PRIMARY KEY (ID),
    CONSTRAINT fk_userData FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE Friends (
    User1 NUMBER,
    User2 NUMBER,
    CONSTRAINT pk_friends PRIMARY KEY (User1, User2),
    CONSTRAINT fk_friends1 FOREIGN KEY (User1) REFERENCES "User" (ID) ON DELETE CASCADE,
    CONSTRAINT fk_friends2 FOREIGN KEY (User2) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE FriendRequest (
    User1 NUMBER,
    User2 NUMBER,
    Approved NUMBER(1) NOT NULL,
    CONSTRAINT pk_friendRequest PRIMARY KEY (User1, User2),
    CONSTRAINT fk_friendRequest1 FOREIGN KEY (User1) REFERENCES "User" (ID) ON DELETE CASCADE,
    CONSTRAINT fk_friendRequest2 FOREIGN KEY (User2) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE PrivateMessage (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Content VARCHAR2(256) NOT NULL,
    TimeStamp TIMESTAMP NOT NULL,
    ToUser NUMBER NOT NULL,
    FromUser NUMBER NOT NULL,
    CONSTRAINT pk_privateMessage PRIMARY KEY (ID),
    CONSTRAINT fk_privateMessage1 FOREIGN KEY (ToUser) REFERENCES "User" (ID) ON DELETE CASCADE,
    CONSTRAINT fk_privateMessage2 FOREIGN KEY (FromUser) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE MediaAlbum (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Name VARCHAR2(128) NOT NULL,
    UserID NUMBER NOT NULL,
    CONSTRAINT pk_mediaAlbum PRIMARY KEY (ID),
    CONSTRAINT fk_mediaAlbum FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE PublicPicture (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Content VARCHAR2(256) NOT NULL,
    AlbumID NUMBER,
    CONSTRAINT pk_publicPicture PRIMARY KEY (ID),
    CONSTRAINT fk_publicPicture FOREIGN KEY (AlbumID) REFERENCES MediaAlbum (ID) ON DELETE SET NULL
);

CREATE TABLE PublicPost (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Text VARCHAR2(256),
    TimeStamp TIMESTAMP NOT NULL,
    Picture NUMBER,
    UserID NUMBER NOT NULL,
    CONSTRAINT pk_publicPost PRIMARY KEY (ID),
    CONSTRAINT fk_publicPost1 FOREIGN KEY (Picture) REFERENCES PublicPicture (ID) ON DELETE CASCADE,
    CONSTRAINT fk_publicPost2 FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE PublicComment (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Content VARCHAR2(256) NOT NULL,
    TimeStamp TIMESTAMP NOT NULL,
    PostID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    CONSTRAINT pk_publicComment PRIMARY KEY (ID),
    CONSTRAINT fk_publicComment1 FOREIGN KEY (PostID) REFERENCES PublicPost (ID) ON DELETE CASCADE,
    CONSTRAINT fk_publicComment2 FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE "Group" (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Name VARCHAR2(128) NOT NULL,
    Logo VARCHAR2(256),
    OwnerID NUMBER NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (ID),
    CONSTRAINT fk_group FOREIGN KEY (OwnerID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE GroupMembers (
    UserID NUMBER,
    GroupID NUMBER,
    CONSTRAINT pk_groupMembers PRIMARY KEY (UserID, GroupID),
    CONSTRAINT fk_groupMembers1 FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE,
    CONSTRAINT fk_groupMembers2 FOREIGN KEY (GroupID) REFERENCES "Group" (ID) ON DELETE CASCADE
);

CREATE TABLE GroupPost (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Text VARCHAR2(256),
    Picture VARCHAR2(256),
    TimeStamp TIMESTAMP NOT NULL,
    GroupID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    CONSTRAINT pk_groupPost PRIMARY KEY (ID),
    CONSTRAINT fk_groupPost1 FOREIGN KEY (GroupID) REFERENCES "Group" (ID) ON DELETE CASCADE,
    CONSTRAINT fk_groupPost2 FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);

CREATE TABLE GroupComment (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1000 INCREMENT BY 1),
    Content VARCHAR2(256) NOT NULL,
    TimeStamp TIMESTAMP NOT NULL,
    PostID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    CONSTRAINT pk_groupComment PRIMARY KEY (ID),
    CONSTRAINT fk_groupComment1 FOREIGN KEY (PostID) REFERENCES GroupPost (ID) ON DELETE CASCADE,
    CONSTRAINT fk_groupComment2 FOREIGN KEY (UserID) REFERENCES "User" (ID) ON DELETE CASCADE
);